Create lambda for send emails
sergiomonz/diggy pull request #11
Opened 2022-05-10 11:34 UTC by 1701722767

2022-05-10 15:15 UTC, nicolascr181 requested changes

2022-05-10 15:15 UTC, nicolascr181 commented on services/notify/functions/email/main.py
> +    def validate(self):
If message is a dictionary, this validation code could be improved

2022-05-10 15:15 UTC, nicolascr181 commented on services/notify/functions/email/main.py
> +        return req.process()
don't forget to return json format
{
 error: "" ,  message: "", data: ""
}

2022-05-10 15:15 UTC, nicolascr181 commented on services/notify/functions/email/main.py
> +        return err
same here

2022-05-10 15:15 UTC, nicolascr181 commented on services/requirements.txt
> +boto3
Is boto3 layer  necessary?,
it's already installed in aws

2022-05-11 00:59 UTC, sergiomonz approved these changes

2022-05-13 14:52 UTC, nicolascr181 approved these changes

2022-05-13 14:57 UTC, merged