create event & some validations
sergiomonz/diggy pull request #13
Opened 2022-05-17 05:34 UTC by nicolascr181

2022-05-17 13:00 UTC, sergiomonz approved these changes

2022-05-17 14:19 UTC, 1701722767 requested changes

2022-05-17 14:19 UTC, 1701722767 commented on services/events/functions/create/main.py
> +    # this will search for dynamoDB table
??

2022-05-17 14:19 UTC, 1701722767 commented on services/events/functions/create/main.py
> +    new_event = json.loads(json.dumps(new_event), parse_float=Decimal)
why this code not have a try catch?

2022-05-17 14:19 UTC, 1701722767 commented on services/events/functions/create/main.py
> +        if not data[name]:
this always is False

2022-05-17 14:24 UTC, nicolascr181 commented on services/events/functions/create/main.py
> +        if not data[name]:
This function raises an exception if it happens, not a true or false value

2022-05-17 23:54 UTC, 1701722767 requested changes

2022-05-17 23:54 UTC, 1701722767 commented on services/events/functions/create/main.py
> +        if not data[name]:
but no validate that exist some keys, only validate that keys of a data exist in data

2022-05-17 23:54 UTC, 1701722767 commented on services/events/functions/create/main.py
> +    # TODO implement
??

2022-05-21 20:42 UTC, 1701722767 requested changes

2022-05-21 20:42 UTC, 1701722767 commented on services/events/functions/create/main.py
> +    new_id = "E" + str(uuid.uuid4())
return the value directly, for not lose memory in this new var

2022-05-21 20:42 UTC, 1701722767 commented on services/events/functions/create/main.py
> +    except Exception as e:
why catcha if thrown again

2022-05-21 20:42 UTC, 1701722767 commented on services/events/functions/create/main.py
> +        print("Error al intentar crear un nuevo evento")
in the general try you can print this errors and evit this

2022-05-21 20:42 UTC, 1701722767 commented on services/events/functions/create/main.py
> +        response['statusCode'] = 500
this can be a 400 status code

2022-05-21 20:42 UTC, 1701722767 commented on services/events/functions/create/main.py
> +        message['error']  = True
add print e

2022-05-21 21:15 UTC, 1701722767 approved these changes

2022-05-21 21:15 UTC, 1701722767 commented on services/events/functions/create/main.py
> +    "max": "Debe ingresar la cantidad maxima de personas al evento",
máxima

2022-05-21 21:15 UTC, merged