some coding improvements added
sergiomonz/diggy pull request #23
Opened 2022-05-21 23:06 UTC by nicolascr181

2022-05-21 23:13 UTC, 1701722767 requested changes

2022-05-21 23:13 UTC, 1701722767 commented on services/auth/functions/confirm/main.py
>  Confirm new user by confirmation_code
this comment is necesary?

2022-05-21 23:13 UTC, 1701722767 commented on services/auth/functions/log-in/main.py
> +    # Getting the user details.
delete this comment

2022-05-21 23:19 UTC, 1701722767 approved these changes

2022-05-23 19:36 UTC, sergiomonz approved these changes

2022-05-24 15:15 UTC, merged