list all places
sergiomonz/diggy pull request #25
Opened 2022-05-22 02:37 UTC by nicolascr181

2022-05-22 02:40 UTC, 1701722767 requested changes

2022-05-22 02:40 UTC, 1701722767 commented on services/places/functions/list/main.py
> +    # TODO implement
delete this

2022-05-22 02:40 UTC, 1701722767 commented on services/places/functions/list/main.py
> +    response = places_table.scan(Limit = PAGE_SIZE)
when paginate the items, need way for get next items

2022-05-24 02:46 UTC, sergiomonz approved these changes

2022-05-24 14:28 UTC, 1701722767 requested changes

2022-05-24 14:28 UTC, 1701722767 commented on services/places/functions/list/main.py
> +        (queryStringParameters['last_evaluated_key'])):
is better if this key is same that other lambda, for not generate confusion in the API

2022-05-24 15:00 UTC, batoJC approved these changes

2022-05-24 15:01 UTC, sergiomonz approved these changes

2022-05-24 15:02 UTC, 1701722767 approved these changes

2022-05-24 15:02 UTC, merged