pop up info for a single event
sergiomonz/diggy pull request #30
Opened 2022-05-25 04:34 UTC by nicolascr181

2022-05-25 04:37 UTC, nicolascr181 commented
![Captura](https://user-images.githubusercontent.com/66856205/170180757-9c9454ba-0db8-45c7-b8ef-22ded1ac0ced.PNG)

2022-05-26 20:09 UTC, nicolascr181 commented
![image](https://user-images.githubusercontent.com/66856205/170568857-64db03b0-fe01-43c8-8a86-2017b8e228b9.png)

2022-05-27 00:20 UTC, 1701722767 requested changes

2022-05-27 00:20 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +    <l-marker :lat-lng="markerLatLng" @click="getEvent">
with this behavior we need have a modal for each marker, I suggest a method that get data, fill the pop up, and show the popo up, and the pop up can be a component

2022-05-27 23:04 UTC, nicolascr181 commented
![image](https://user-images.githubusercontent.com/66856205/170798705-4870304a-db8e-4c14-a7cd-6f2a84ddef48.png)

2022-05-28 18:29 UTC, 1701722767 requested changes

2022-05-28 18:29 UTC, 1701722767 commented on dashboard/src/components/Directory/Container.vue
> +
delete space

2022-05-28 18:29 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +        this.$refs.PopUp.show('/find', this.params);
the params can be a param in the method

2022-05-28 18:29 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +        this.$refs.PopUp.show('/find', this.params);
/events/find not?

2022-05-28 22:51 UTC, 1701722767 approved these changes

2022-05-29 02:35 UTC, sergiomonz approved these changes

2022-05-29 02:45 UTC, merged