allow origin added & category_id changed to id
sergiomonz/diggy pull request #36
Opened 2022-05-28 00:31 UTC by nicolascr181

2022-05-28 16:47 UTC, 1701722767 requested changes

2022-05-28 16:47 UTC, 1701722767 commented on services/places/functions/create/main.py
> +    def put_category(self,category_id):
get_category_name is better name

2022-05-28 16:47 UTC, 1701722767 commented on services/places/functions/create/main.py
> +        places_data["category"] = category
category_name*

2022-05-28 22:36 UTC, 1701722767 approved these changes

2022-05-29 02:35 UTC, sergiomonz approved these changes

2022-05-29 02:37 UTC, merged