show events in map & show current position user
sergiomonz/diggy pull request #38
Opened 2022-05-30 21:28 UTC by nicolascr181

![image](https://user-images.githubusercontent.com/66856205/171060728-e17cfbf4-bd8c-4811-93e1-55ff0de68fa4.png)

2022-05-30 21:32 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +        console.log(this.events)
delete this

2022-05-30 21:32 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
>        .then((res) => {
validate that not return error

2022-05-30 21:32 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +
show error when anything fail

2022-05-30 21:32 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +      onLocationFound(l) {
what is l?

2022-05-30 21:32 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +        console.log(l);
delete this

2022-05-30 22:04 UTC, sergiomonz approved these changes

2022-05-30 23:51 UTC, 1701722767 requested changes

2022-05-30 23:51 UTC, 1701722767 commented on dashboard/src/components/Events/Register.vue
> +    transformDate(date){
this can be a helper?

2022-05-31 20:06 UTC, 1701722767 approved these changes

2022-05-31 20:06 UTC, merged