Place register
sergiomonz/diggy pull request #39
Opened 2022-05-31 18:42 UTC by sergiomonz

Creación de lugar y modificación de registro de eventos. Adición de text area.

![image](https://user-images.githubusercontent.com/68119067/171261647-8be883a8-937d-4fd4-80a3-1b7dc98695ed.png)

2022-05-31 20:09 UTC, 1701722767 requested changes

2022-05-31 20:09 UTC, 1701722767 commented on dashboard/src/components/Events/Register.vue
> +                        label="Descripción del lugar"
why change this component?

2022-05-31 20:09 UTC, 1701722767 commented on dashboard/src/components/Places/Register.vue
> +                          <h1>Seleccione la ubicación del evento</h1>
lugar*

2022-05-31 20:09 UTC, 1701722767 commented on dashboard/src/components/Places/Register.vue
> +
add message that register was success

2022-05-31 20:24 UTC, sergiomonz commented on dashboard/src/components/Events/Register.vue
> +                        label="Descripción del lugar"
Fixed*

2022-05-31 20:24 UTC, sergiomonz commented on dashboard/src/components/Places/Register.vue
> +                          <h1>Seleccione la ubicación del evento</h1>
Fixed*

2022-05-31 20:27 UTC, sergiomonz commented on dashboard/src/components/Places/Register.vue
> +
Done

2022-05-31 20:29 UTC, 1701722767 requested changes

2022-05-31 20:29 UTC, 1701722767 commented on dashboard/src/components/Places/Register.vue
> +          notification({
mmm is not the correct place

2022-06-02 01:20 UTC, nicolascr181 approved these changes

2022-06-02 18:15 UTC, 1701722767 approved these changes

2022-06-02 18:15 UTC, merged