show places in map and center user position
sergiomonz/diggy pull request #40
Opened 2022-05-31 23:37 UTC by nicolascr181

![image](https://user-images.githubusercontent.com/66856205/171300719-a959f8e9-6360-4a11-a191-7848fa94ab3a.png)

2022-05-31 23:43 UTC, nicolascr181 commented
![image](https://user-images.githubusercontent.com/66856205/171301214-30cb69a0-8c2c-40d6-ae5b-a72796ccc0ed.png)

2022-06-02 18:29 UTC, 1701722767 requested changes

2022-06-02 18:29 UTC, 1701722767 commented on dashboard/src/components/ShowPlace.vue
> +                {{this.model.score}} ({{this.model.comments}})
I suggest change the comments name

2022-06-02 20:18 UTC, nicolascr181 commented on dashboard/src/components/ShowPlace.vue
> +                {{this.model.score}} ({{this.model.comments}})
ready

2022-06-02 20:26 UTC, sergiomonz approved these changes

2022-06-02 20:27 UTC, 1701722767 approved these changes

2022-06-02 20:27 UTC, merged