create-lambda-for-putting-comments
sergiomonz/diggy pull request #45
Opened 2022-06-03 03:34 UTC by nicolascr181

![image](https://user-images.githubusercontent.com/66856205/171780936-d016d2d1-fe6a-4dec-9d20-c20cf6cc61d7.png)
![image](https://user-images.githubusercontent.com/66856205/171781051-5645ddd7-6a9a-41e6-b9f5-526f600f4e95.png)

2022-06-03 20:00 UTC, 1701722767 requested changes

2022-06-03 20:00 UTC, 1701722767 commented on dashboard/src/components/ShowEvent.vue
> +                {{this.model.score}} ({{this.model.total_comments}})
why duplicate the score?

2022-06-03 20:00 UTC, 1701722767 commented on services/events/functions/create/main.py
>          "datestart": event['datestart'],
I suggest date_start is a better nomenclature

2022-06-03 23:45 UTC, nicolascr181 commented on dashboard/src/components/ShowEvent.vue
> +                {{this.model.score}} ({{this.model.total_comments}})
One of them is the attr of the component, the starts , the other one is for the user to see. That's how it was made the v-card component.

2022-06-03 23:45 UTC, nicolascr181 commented on dashboard/src/components/ShowEvent.vue
> +                {{this.model.score}} ({{this.model.total_comments}})
One of them is the attr of the component, the starts , the other one is for the user to see. That's how it was made the v-card component.

2022-06-03 23:49 UTC, nicolascr181 commented on dashboard/src/components/ShowEvent.vue
> +                {{this.model.score}} ({{this.model.total_comments}})
![image](https://user-images.githubusercontent.com/66856205/171967621-e843f224-49ea-453c-b515-230bbd8ab625.png)

2022-06-04 02:33 UTC, nicolascr181 commented
![image](https://user-images.githubusercontent.com/66856205/171974865-66991d83-ab5b-4707-bea9-cdaa4393cd16.png)

2022-06-04 02:42 UTC, 1701722767 approved these changes

2022-06-04 13:05 UTC, sergiomonz approved these changes

2022-06-04 13:05 UTC, merged