get closest events by latitude and longitude
sergiomonz/diggy pull request #52
Opened 2022-06-18 22:05 UTC by nicolascr181

![image](https://user-images.githubusercontent.com/66856205/174458459-0047702f-c311-4208-bbbb-d755fb81b12f.png)

2022-06-18 22:32 UTC, sergiomonz approved these changes

2022-06-18 22:34 UTC, 1701722767 requested changes

2022-06-18 22:34 UTC, 1701722767 commented on dashboard/src/components/Directory/Map.vue
> +        console.log(currentCenter.lat);
delete this

2022-06-18 22:34 UTC, 1701722767 commented on services/events/functions/list-closest/main.py
> +def distance(coordinates1,coordinates2):
is posible doing in query to dynamo with this validation?

2022-06-19 16:00 UTC, 1701722767 approved these changes

2022-06-19 16:00 UTC, 1701722767 commented on .github/workflows/deploy.yml
> +    branches: [create-lambda-for-closest-events]
😑

2022-06-19 16:00 UTC, merged