create-lambdas-for-sns.push
sergiomonz/diggy pull request #60
Opened 2022-06-20 22:59 UTC by nicolascr181

![image](https://user-images.githubusercontent.com/66856205/174686879-0c1743b1-d4de-499e-a989-913e7619b64e.png)

2022-06-20 23:16 UTC, sergiomonz approved these changes

2022-06-21 14:10 UTC, 1701722767 requested changes

2022-06-21 14:10 UTC, 1701722767 commented on services/notify/functions/push-send/main.py
> +        'statusCode': 200,
this lambda is connect to apigatwey?

2022-06-22 02:30 UTC, 1701722767 requested changes

2022-06-22 02:30 UTC, 1701722767 commented on dashboard/src/services/Firebase.js
> +            .catch((err)=>{
notify this error to user

2022-06-22 03:00 UTC, merged